# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Meta data
title: 'Mylene'
author: ''
description: 'Mylene.eu'

# Site navigation
navigation:
  - title: Homeparties
    url: '#!'
  - title: Consulente worden
    url: '#!'
  - title: Over Mylene
    url: '#!'
  - title: Blog
    url: '#!'
  - title: Contact
    url: '#!'

# Jekyll settings
permalink: pretty

# Exclude these files from the build process
exclude: ['_site','scss','*scss','Gem*','Guard*','*rb','.sass-cache','.git*','config.rb','*.md','*.json','docroot','node_modules','gulpfile.js','install.sh','lint.yml']
